
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0022:Use block body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:JustReadCollection.Model.IListExtensions.AsJustReadCollection``1(System.Collections.Generic.IList{``0})~JustReadCollection.Model.JustReadCollection{``0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0022:Use block body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:JustReadCollection.Model.JustReadCollection`1.ToList~System.Collections.Generic.List{`0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0022:Use block body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:JustReadCollection.Model.JustReadCollection`1.List~System.Collections.Generic.List{`0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0022:Use block body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.ReadCollection.IListExtensions.AsJustReadCollection``1(System.Collections.Generic.IList{``0})~Software9119.ReadCollection.JustReadCollection{``0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0022:Use block body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.ReadCollection.JustReadCollection`1.List~System.Collections.Generic.List{`0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0022:Use block body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.ReadCollection.JustReadCollection`1.Array~`0[]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0022:Use block body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.ReadCollection.IListExtensions.AsSwiftReadCollection``1(System.Collections.Generic.IList{``0})~Software9119.ReadCollection.SwiftReadCollection{``0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0022:Use block body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.ReadCollection.Auxiliary.CollectionExtensionsAux.ReturnNull(System.Collections.IEnumerable,System.Boolean)~System.Boolean")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0022:Use block body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.ReadCollection.CollectionExtensions.AsJustReadCollection``1(System.Collections.Generic.IList{``0})~Software9119.ReadCollection.JustReadCollection{``0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.ReadCollection.CollectionExtensions.ToIList``1(System.Collections.Generic.IEnumerable{``0})~System.Collections.Generic.IList{``0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.ReadCollection.JustReadCollection`1.CopyFromItems(`0[]@,System.Int32,System.Int32@)")]